### ISSUE TITLE
DocOnMac

### ISSUE THREAD

**Issue by DocOnMac** [AndreasVerhoeven/NoMailAppAnimationsOnMavericks#10]
Hi,
Will you be releasing an El Capitan version of DisableMailAnimationsForOSX please?

**Comment by AndreasVerhoeven** [comment]
Yep, I need the UDID from Info.plist only probably (see the README on how to get that UDID).

**Comment by DocOnMac** [comment]
I am not a power user, what does that actually mean please.
Will it be a simple download like Yosemite and Mavericks?

**Comment by AndreasVerhoeven** [comment]
Yep.
