### ISSUE TITLE
Support for macOS Sierra?

### ISSUE THREAD

**Issue by posburn75** [AndreasVerhoeven/NoMailAppAnimationsOnMavericks#17]
Are there plans to make this plugin compatible with Sierra? Manually adding the Sierra Mail.app UUID to AveNoAnimationsInMailPlugin-Info.plist and rebuilding the app failed to remove the animations.

I'm using Sierra build 16A304a BTW.

**Comment by AndreasVerhoeven** [comment]
I don't have Sierra installed yet, but once I have, I'll find a way - hopefully - to make it work

**Comment by AndreasVerhoeven** [comment]
Added the latest UDID, but don't have Sierra myself due to compatibility problems.

**Comment by AndreasVerhoeven** [comment]
This is fixed with the latest release :)

**Comment by posburn75** [comment]
In my case, I get an "incompatible plugin error" when installing the latest version of the plugin on Sierra 10.12.1 Beta (16B2333a). This is partially address by using [MailPluginFix](https://code2k.net/products/mailpluginfix/), but this only turns of the animation for "reply" or "forward". It does not turn off the animation for "send".

**Comment by AndreasVerhoeven** [comment]
The send animation has been broken by Sierra. I will have to dive into that

**Comment by PFBG** [comment]
Andreas, thank you very much for your work on this. Those animations are pretty annoying. I can't imagine how people at Apple look at this and say "nice! let's use it."...

**Comment by skhub1** [comment]
Hey Andreas! Were you able to get this working properly on Sierra? I really appreciate the work you do on this - the animations make me feel seasick!! Thanks!

**Comment by MikeMaxNow** [comment]
It's not working on 10.12.2.

This is so sad. Can anybody PLEASE fix this???

Thank you so much, I would really appreciate it!

**Comment by MikeMaxNow** [comment]
I was able to get it working on 10.12.2 by using the free tool "MailPLuginFix" to change the UUIDs.

**Comment by bhaller** [comment]
I just logged a bug on Apple regarding this, asking that they at least add a user default that we can set in Terminal to turn the animations off.  I'd suggest that anybody else here who has access to Bug Reporter might do the same.  In the meantime: MikeMaxNow, can you describe in more detail what you did to get it working on 10.12.2, from beginning to end (assuming a fresh install of 10.12.2, in other words)?  Thanks!

**Comment by MikeMaxNow** [comment]
Sure:

1. Quit Mail.app

2. Install NoMailAppAnimations (current version).

3. Launch Mail.app and let it reject the outdated plugin.

4. Quit Mail.app.

5. Run MailPLuginFix from here: https://code2k.net/products/mailpluginfix/ and select NoMailAppAnimations in MailPLuginFix, let it fix the selected plugin.

6. Quit MailPLuginFix.

7. Launch Mail.app

**Comment by bhaller** [comment]
Thanks MikeMaxNow.  That did the trick for getting rid of the Reply animation.  The Send animation, where the window glides upwards off the screen, is still active.  Sigh.  Well, thanks.  Maybe someday Apple will get rid of this.

**Comment by AndreasVerhoeven** [comment]
The latest release has support for macOS Sierra 10.12.2 and should fix the send animation to be disabled again :)

**Comment by bhaller** [comment]
Works perfectly for me on 10.12.2.  Thanks Andreas.

**Comment by MikeMaxNow** [comment]
It works, thank you! :-)

**Comment by bhaller** [comment]
...aaaand it looks like it doesn't work again in 10.12.4.  Apple's update removed it for me, as being incompatible.  Sigh.

**Comment by MikeMaxNow** [comment]
I fixed it again by using MailPLuginFix, see my post above on how to do it!
