### ISSUE TITLE
Don't require administrative permissions?

### ISSUE THREAD

**Issue by rawtaz** [AndreasVerhoeven/NoMailAppAnimationsOnMavericks#19]
If all that's needed is to place a file/folder in the ~/Library/Mail/Bundles directory and run a `defaults` command, both of them as the current user, why does the installer ask for administrative privileges?

**Comment by AndreasVerhoeven** [comment]
Good question! Probably the default of the tool I used to create the installer. Will investigate!

**Comment by AndreasVerhoeven** [comment]
It's because the installer defaults to "Install for all users of this computer". Will have to check on how to change that

**Comment by rawtaz** [comment]
Yeah, that must be it. I've seen installers offer "for current user only" or similar.

Once you find that setting it'll probably be alright.

BTW, I did download the latest release, and it doesn't work on OS X 10.9.5 Mavericks, Mail is 7.3 and it complains about the version of the bundle not being compatible.


3 okt 2017 kl. 18:15 skrev Andreas Verhoeven <notifications@github.com>:

**Comment by AndreasVerhoeven** [comment]
For the bundle not being compatible, there's a part in the readme on "How to Build for new Mail versions?"

**Comment by rawtaz** [comment]
Yeah, I found that but in the end I just used an older version.

I was surprised though, I thought that the latest version covered all of the OS versions, but I suppose that's simply not the case.

Either way, it works now, thanks a lot for this!


3 okt 2017 kl. 21:50 skrev Andreas Verhoeven <notifications@github.com>:

**Comment by AndreasVerhoeven** [comment]
Looked into the installer situation; main problem is that the software that I used to make the installer - PackageMaker - is no longer supported by Apple, so I cannot update the installer.
