### ISSUE TITLE
macos High Sierra

### ISSUE THREAD

**Issue by wamatt** [AndreasVerhoeven/NoMailAppAnimationsOnMavericks#20]
Hi Andrease

Kudos on a nice project. :) My enthusiasm however, was a recently subdued somewhat after upgrading to macos High Sierra (10.13)

```
Mail has disabled the following plug-ins:

	AveNoAnimationsInMailPlugin

Contact the makers of these plug-ins for versions that are compatible with Mail 11.0.
```

These mail.app animations are just terrible. Is it a big pain to get this working on macos 10.13? I don't mind delving into Xcode if necessary or helping out

**Comment by AndreasVerhoeven** [comment]
Hi wamatt,

I'm currently not yet running High Sierra, because of the huge amount of bugs in it, but
there's a section on this in the projects README: How to Build for new Mail versions?

Let me know how that works for you.

**Comment by wamatt** [comment]
Ok great. Let me try give that a go. Will keep you posted

**Comment by wamatt** [comment]
Works great, thank you!
