### ISSUE TITLE
Mountain Lion compatibility

### ISSUE THREAD

**Issue by shape55** [AndreasVerhoeven/NoMailAppAnimationsOnMavericks#24]
Do none of these work on Mountain Lion? I tried using the Terminal commands but for some reason they are not working on either Mountain Lion or Sierra (2 different macs) using these commands:

defaults write com.apple.Mail DisableSendAnimations -bool YES
defaults write com.apple.Mail DisableReplyAnimations -bool YES
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool NO

thanks

**Comment by AndreasVerhoeven** [comment]
Nope, that's what this plugin is for.

**Comment by shape55** [comment]
ok, thanks
