### ISSUE TITLE
Update for mail 8.2?

### ISSUE THREAD

**Issue by uscrules1** [AndreasVerhoeven/NoMailAppAnimationsOnMavericks#9]
I updated mail today but now my plugin isn't working.  Can you please update and re-post?  Thanks!

**Comment by AndreasVerhoeven** [comment]
Do you have the UDID for the new OSX? I personally don't run Yosemite, but Mavericks. 

Please see "How to Build for new Mail versions?" of the read me

**Comment by uscrules1** [comment]
Yes, here that is: 60D52D22-7491-4CA7-95BA-88215BD88F8E


I don’t run xcode so I can’t update past this.

Thanks.

**Comment by AndreasVerhoeven** [comment]
Thanks, please see: https://github.com/AndreasVerhoeven/NoMailAppAnimationsOnMavericks/releases/tag/1.1.2

**Comment by uscrules1** [comment]
Wow - thanks for the quick response!  I just installed but am still getting the error on open and the animations.

**Comment by AndreasVerhoeven** [comment]
Can you try? https://github.com/AndreasVerhoeven/NoMailAppAnimationsOnMavericks/blob/master/Output/DisableMailAnimationsForOSX.pkg

**Comment by uscrules1** [comment]
Nope, error still on mail open.

**Comment by AndreasVerhoeven** [comment]
Hmm, can you delete everything in ~/Library/Mail/Bundles/ that's related to this plugin and reinstall? Thanks!

**Comment by uscrules1** [comment]
Deleted bundles, ran installer - still getting error.

**Comment by AndreasVerhoeven** [comment]
Another option: can you copy https://github.com/AndreasVerhoeven/NoMailAppAnimationsOnMavericks/tree/master/Output/AveNoAnimationsInMailPlugin.mailbundle/Contents to ~/Library/Mail/Bundles/ and restart Mail.app?

**Comment by AndreasVerhoeven** [comment]
Scratch that - I see what's wrong. There's a hidden space in the UDID :) Gonna fix that now

**Comment by AndreasVerhoeven** [comment]
This one should work: https://github.com/AndreasVerhoeven/NoMailAppAnimationsOnMavericks/releases/download/1.1.2/DisableMailAnimationsForOSX.pkg

**Comment by uscrules1** [comment]
Boom!  That did it - working!  thank you!!
